- backend/src/api/auth/auth.controller.ts
- backend/src/api/auth/service/login.service.ts
cookie option 어떻게 해야할지 몰라서 일단 이렇게 해봅니다
> fix: cookie option test

- frontend/Dockerfile
- frontend/nginx.conf
docker compose에 front 용 환경변수 추가
* REACT_APP_SERVER
> feat: docker compose에 환경변수 추가

- docker-compose.yml
> feat: REACT_APP_SERVER 환경변수 추가

- backend/src/api/auth/auth.controller.ts
- backend/src/api/auth/service/login.service.ts
> feat: cookie option secure

- .script/deploy.sh
- backend/src/api/auth/service/login.service.ts
cookie option 에 local 일땐 secure 안쓰도록
> feat: cookie option local added

- .script/deploy.sh
- docker-compose.yml
백엔드 로컬용 서버띄우는데 포트 번호 잘못입력했네요..
> fix: port 번호 잘못 입력함

- backend/Dockerfile
backend Dockerfile run을 하나로 묶어서 좀더 최적화해봤슴다
> feat:  DOckerfile run 하나로 묶음

- .script/deploy.sh
> feat: db port 도 바꾼다

- frontend/package.json
> feat: local https 추가

- backend/src/api/auth/auth.controller.ts
- backend/src/api/auth/service/login.service.ts
- backend/src/app.module.ts
- backend/src/common/filter/http-exception.filter.ts
* http exception filter 추가했습니다.
* debug 용 jwt api 추가 했습니다. jwt 알고 싶은사람 요청보내서 받아올 수 있습니다. 개발 단계에서만 사용해주시길 바랍니다.
* 로그아웃 api 고침
> Feat: http exception filter 추가 및 debug 용 jwt api 추가

- backend/src/socket/events/events.gateway.ts
> fix: emit all

- frontend/src/common/MainLayout/UserMenu.tsx
- frontend/src/hooks/useCheckLogin.ts
- frontend/src/hooks/useHandleSocket.ts
소켓 두번 연결되는 이슈가 있어서 어떻게든 해결했습니다.
로그아웃되면 login 페이지로 다시 돌아가도록 수정했습니다.
> fix: 소켓 두번 연결되는거 해결

- backend/package.json
- backend/src/app.module.ts
- backend/src/common/adapter/socket-io.adapter.ts
- backend/src/common/filter/ws-exception.filter.ts
- backend/src/common/guard/jwt-auth/index.ts
- backend/src/common/guard/jwt-auth/jwtPayload.ts
- backend/src/common/guard/jwt-auth/req-jwt-payload.ts
- backend/src/common/guard/jwt-auth/socket-jwt-auth.guard.ts
- backend/src/common/guard/jwt-auth/socket-jwt-payload.ts
- backend/src/main.ts
- backend/src/socket/events/events.gateway.ts
- backend/src/socket/events/events.module.ts
- backend/yarn.lock
> feat: socket auth 추가

- backend/src/socket/connection-handle/connection-handle.gateway.ts
connection gateway 에 injectable 이 없어서 DI가 안되고 있었네요
> fix: hotfix connection gateway injectable

- backend/src/socket/chat/chat.gateway.ts
- backend/src/socket/chat/dto/incoming/update-chat-room.dto.ts
> fix: update room dto id

- backend/src/api/auth/auth.controller.ts
- backend/src/api/auth/service/login.service.ts
보안같은거 다 말아먹고 다른 사람이름으로 로그인 할 수 있는 디버깅용 api 추가 했습니다. (왠만하면 개발용으로만 씁시다)
> feat: 디버깅용 api 추가

- backend/src/api/auth/auth.controller.ts
보안상 다른사람으로 로그인은 문제가 될거같아서 그냥 랜덤한 이름으로 로그인되게 바꿨씁니다.
> fix: 랜덤 로그인으로 수정

- backend/src/socket/chat/chat.gateway.ts
- backend/src/socket/chat/service/chat-user.service.ts
> feat: 비밀번호 대조 로직 추가

- backend/src/api/user/dto/update-user-profile-request.dto.ts
> feat: update avatar

- backend/src/api/user/service/find-user.service.ts
> fix: 유저 못찾을때 에러 내용 수정

- backend/src/api/user/service/find-user.service.ts
> fix: await 빼먹ㅇㅇㅁ

- backend/src/socket/chat/repository/chat-room.repository.ts
- backend/src/socket/chat/service/chat-room.service.ts
- backend/src/socket/chat/service/chat-user-operate.service.ts
- backend/src/socket/chat/service/chat-user.service.ts
> refactor: 밴관련 로직 리펙토링 했슴다

- backend/src/socket/game/dto/outcoming/game-room.dto.ts
- backend/src/socket/game/model/game-room.ts
- backend/src/socket/game/repository/game-room.repository.ts
> fix: 소켓 연결 해제되면 게임룸도 삭제

- backend/src/socket/chat/chat.gateway.ts
- backend/src/socket/chat/dto/incoming/leave-chat-room.dto.ts
- backend/src/socket/chat/repository/chat-room.repository.ts
- backend/src/socket/chat/service/chat-user.service.ts
- backend/src/socket/game/game.gateway.ts
채팅방 나가는 부분 리펙토링 했습니다 사실상 나갈때 모든 socket을 방에서 내쫒으면 되는거라 따로 roomId를 받을 필요가 없었네요
> Refactor/socket leave + add game leave

- backend/src/socket/game/game.module.ts
> fix: 디펜던시 빠진거수정

- backend/src/api/auth/dto/request/register.dto.ts
왠진 모르겠는데 IsOptinal이 끼어있었네요 그래서 DTO 단에서 null이 validate 가 안되고 있었습니다. 수정했습니다.
> fix: 백엔드 user avatar null 에러 나는거 수정

- frontend/src/pages/GamePage/MainScene.tsx
- frontend/src/pages/GamePage/game.tsx
* Close #121 
* 어느 Player든 5점을 먼저 획득하면 게임이 종료 됩니다.
* 게임이 종료되면 `/game`으로 이동합니다.
* 원조 Pong(1972)는 11점이지만 Play-time이 너무 길어져서 5점으로 조정
* score관련 함수들을 묶어서 `checkScore()`로 만듬.
* 게임이 끝나면 게임 결과 페이지로 이동하도록 구현할 예정입니다.
> Pong: 게임 승리 판정

- frontend/src/services/axiosWrapper.ts
axios 에서 body를 아무 객체 형태가 아니라 { data: <객체> } 형태로만 받아서 생긴 문제였습니다.
일단 급해보여서 급하게 피알올려요 (그래서 fix/ui인거 양해부탁,,)
> !HOTFIX: delete 401 에러 수정

- backend/src/api/user/dto/request/check-duplicate-nickname.dto.ts
- backend/src/api/user/service/update-profile.service.ts
- backend/src/api/user/user.controller.ts
> feat: 닉네임 중복 체크 api 추가

- backend/src/api/user/service/update-profile.service.ts
- backend/src/api/user/user.controller.ts
> feat: 2차 인증 제거

- backend/src/api/user/user.controller.ts
> fix: 2차 인증 이름 변경

- frontend/src/App.tsx
- frontend/src/common/constants.ts
- frontend/src/hooks/index.ts
- frontend/src/hooks/useGetMatchHistoryById.ts
- frontend/src/hooks/useGetUser.ts
- frontend/src/hooks/useTwoFactorLogin.ts
- frontend/src/pages/ProfilePage/TwoFactorAuth/Cancle2FA.tsx
- frontend/src/pages/ProfilePage/TwoFactorAuth/Enable2FA.tsx
- frontend/src/pages/ProfilePage/TwoFactorAuth/GithubCallback.tsx
- frontend/src/pages/ProfilePage/TwoFactorAuth/TwoFactorAuth.style.ts
- frontend/src/pages/ProfilePage/TwoFactorAuth/TwoFactorAuth.tsx
- frontend/src/pages/ProfilePage/TwoFactorAuth/index.ts
- frontend/src/services/deleteTwoFactorAuth.ts
- frontend/src/services/getGithubCallbackCode.ts
- frontend/src/services/index.ts
- frontend/src/store/dummy2FA.ts
- frontend/src/types/profile.d.ts
- frontend/src/types/user.d.ts
1. 2차인증 더미 삭제
2. 2차인증 get, delete API 추가
3. 2차인증 생성, 삭제 버튼 구현
> Feat/profile TFA  API add

- backend/src/common/utils/index.ts
- backend/src/common/utils/sleep.ts
- backend/src/socket/game/dto/incoming/spectate-game-room.dto.ts
- backend/src/socket/game/game.gateway.ts
- backend/src/socket/game/repository/game-room.repository.ts
- backend/src/socket/game/service/finish-game.service.ts
- backend/src/socket/game/service/game-play.service.ts
- backend/src/socket/game/service/game-user.service.ts
백엔드 관전자 추가했씁니다. 아직 프론트와 협의중이고 중간 과정에서 pr 한번 올립니다.
> feat: 백엔드 꽌전자추가

- frontend/src/hooks/useHandleSocket.ts
- frontend/src/hooks/useSetSocketHandler.ts
- frontend/src/pages/GameListPage/GameRoomElement.tsx
- frontend/src/pages/GameListPage/NewGameModalBody.tsx
- frontend/src/pages/GamePage/GamePong.tsx
- frontend/src/pages/GamePage/MainScene.tsx
- frontend/src/pages/GamePage/index.tsx
- frontend/src/store/index.ts
- frontend/src/store/joinSpectateRoomState.ts
- frontend/src/store/playerRoleState.ts
- frontend/src/types/game.d.ts
구현함 대단함 야호
* close #134 
* close #165
> Pong: 입장, 및 관전 기능 구현

- backend/src/socket/chat/model/chat-room.ts
- backend/src/socket/chat/service/chat-room.service.ts
- backend/src/socket/chat/service/chat-user-operate.service.ts
- backend/src/socket/chat/service/chat-user.service.ts
unban 에서 set delete를 reference 로 해야하는데 value로 된다고 생각해서 unban이 안되고 있었네요 
그냥 타입을 바꿨습니다.
> fix : unban

- backend/src/api/achievement/achievement.module.ts
제가 가끔 게임하는 보드게임 아레나에서 이미지파일 따오고 업적같게 만들었습니다~
뭐 없어요
> fix: 업적 세부정보 수정 및 이미지 url추가

- frontend/src/pages/GamePage/GamePong.tsx
- frontend/src/pages/GamePage/MainScene.tsx
1. 게임 방을 생성후 임의로 나가기 
2. 다시 방을 생성
3. Phaser 생성 안됨
* @Skyrich2000 님이 삭제 예제코드에 가이드 줘서 해결
> Fix: Pong Phaser 재실행시 터지는 issue

- backend/src/socket/game/dto/incoming/create-game-room.dto.ts
- backend/src/socket/game/game.gateway.ts
- backend/src/socket/game/repository/game-room.repository.ts
- backend/src/socket/game/service/game-room.service.ts
> feat: create room mode

- backend/src/api/user/user.controller.ts
- frontend/src/common/constants.ts
- frontend/src/pages/RegisterPage/index.tsx
- frontend/src/services/postUserCheckDuplicateNickname.ts
> feat: 닉네임 중복 체크 활성화

- backend/src/api/file/file.controller.ts
- frontend/src/pages/RegisterPage/index.tsx
> feat: deafult 이미지 빼머기음

- frontend/src/pages/ChatPage/index.tsx
- frontend/src/pages/RegisterPage/index.tsx
> Fix/register loading image + 차단한사람은 채팅 안보이게

- frontend/src/pages/GamePage/index.tsx
* close #197 
요구사항 충족을 위해 게임 플레이 방법을 Pong 하단에 출력
> Pong: 게임 설명 추가

- backend/src/api/auth/auth.controller.ts
- backend/src/api/auth/service/cookie.service.ts
- backend/src/api/auth/service/two-factor.service.ts
- backend/src/socket/chat/dto/outcoming/chat-room.dto.ts
- backend/src/socket/chat/service/chat-room.service.ts
- frontend/src/App.tsx
- frontend/src/common/constants.ts
- frontend/src/hooks/useLogin.ts
- frontend/src/hooks/useTwoFactorLogin.ts
- frontend/src/pages/GithubCallbackPage/index.tsx
- frontend/src/pages/ProfilePage/TwoFactorAuth/Enable2FA.tsx
- frontend/src/pages/ProfilePage/TwoFactorAuth/index.ts
- frontend/src/pages/index.ts
- frontend/src/utils/error/throwApiError.ts
> fix: 2차인증 로그인할떄 하도록 수정

- backend/src/socket/game/service/finish-game.service.ts
> feat: point 연산 추가

- backend/src/socket/game/game.gateway.ts
- backend/src/socket/game/service/game-user.service.ts
게임방 중간에 나갈때도 emitRoom 하도록 했습니다.
> hotfix: leave 할때도 emitRom

- backend/src/socket/game/service/game-user.service.ts
leave game 할때 isGameFinished 빼먹음 ㅎ
> hotfix: leave game 할때 isGameFinished 빼먹음 ㅎ

- backend/src/socket/chat/service/chat-user.service.ts
> fix: 비밀번호 compare 로직 수정

- frontend/src/pages/ProfilePage/ProfileHeader/index.tsx
> feat: 프로필에서 spectate 기능 추가

- backend/src/socket/game/game.gateway.ts
- backend/src/socket/game/service/game-user.service.ts
> fix: spectate self

- backend/src/socket/game/service/game-match-queue.service.ts
> fix: 매치메이킹 중간중간 안먹는 오류 해결

- frontend/src/pages/ChatListPage/ChatListPage.styles.ts
- frontend/src/pages/ChatListPage/ChatRoomElement.styles.ts
- frontend/src/pages/ChatListPage/ChatRoomElement.tsx
- frontend/src/pages/ChatListPage/NewChatModalBody.styles.ts
- frontend/src/pages/ChatListPage/NewChatModalBody.tsx
- frontend/src/pages/ChatListPage/index.tsx
- frontend/src/pages/ChatPage/ChatModal/ChatInfoModalBody.tsx
- frontend/src/pages/ProfilePage/ProfileHeader/EditProfileSection.styles.ts
- frontend/src/pages/ProfilePage/ProfileHeader/EditProfileSection.tsx
채팅방 안쪽은 노노
@devleomk1 님의 게임리스트 방 작업 수월화를 위해 먼저 머지 하겟습니다
> Style: 채팅 모달, 채팅 방 리스트 디자인

- .script/deploy.sh
- backend/src/common/database/repository/game-match-queue.repository.ts
- backend/src/socket/chat/service/chat-room.service.ts
- backend/src/socket/game/service/game-match-queue.service.ts
> fix: 능지 이슈

- frontend/src/styles/reset.css
> HOTFIX: 배포판에서 스크린 깨지는거 왜깨지는지몰르겠음

- frontend/src/common/Input/index.tsx
> fix:onclhage

- frontend/src/pages/ChatPage/ChatInput.tsx
> fix:maxlength

- frontend/src/pages/ChatPage/GameInviteModal/GameInviteModalBody.styles.ts
- frontend/src/pages/ChatPage/index.tsx
> fix: 게임 초대 모달 CSS 수정

- backend/src/common/database/model/game-match-queue.ts
- backend/src/common/database/repository/game-match-queue.repository.ts
코드 뜯다가 interface를 model로 분리했어야했는데 안한게 보여서 ㅎㅎㅎㅎ;;;
사소한 풀리퀘 올려놓읍니다
> fix: interface 분리
